config/routes.rb
Rails.application.routes.draw do
  root to: 'aparelhos#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :aparelhos
end

app/models/aparelho.rb
class Aparelho < ApplicationRecord
  validates :numero, presence: true
  validates :operadora, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/aparelhos_controller.rb
class AparelhosController < ApplicationController
  before_action :set_aparelho, only: [:show, :update, :destroy]

  def index
    @aparelhos = Aparelho.all
   # render json: @aparelhos
  end

  def show
   # render json: @aparelho
  end

  def new
  end

  def create
    @aparelho = Aparelho.new(aparelho_params)
    if @aparelho.save
      redirect_to aparelhos_path
     # render json: @aparelho, status: :created, location: @aparelho
    else
    #  render json: @aparelho.errors, status: :unprocessable_entity
    end
  end


  def update
    if @aparelho.update(aparelho_params)
     # render json: @aparelho
    else
     # render json: @aparelho.errors, status: :unprocessable_entity
    end
    
  end

  def destroy
    @aparelho.destroy
    redirect_to aparelhos_path
  end

  private

  def set_aparelho
    @aparelho = Aparelho.find(params[:id])
  end

  def aparelho_params
    params.require(:aparelho).permit(:numero, :operadora, :status)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/aparelhos/edit.html.erb
<div class="container mt-2 pb-2">
<h1>Cadastre um novo aparelho</h1>
  <%= simple_form_for @aparelho do |f| %>
    <%= f.input :numero %>
    <%= f.input :operadora %>
    <%= f.input :status, :as => :boolean, label: 'Ativo'%>
    <div class="d-flex justify-content-between">
      <%= f.submit "Cadastrar", class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/aparelhos/index.html.erb
<div class="index-section">
  <h1 id="index-title"></h1>

  <div class="aparelhos">
    <% @aparelhos.each do |aparelho| %>
      <div class="card-aparelhos">
        <div class="card-aparelhos-infos">
          <p><%= aparelho.operadora.capitalize %></p>
          <p><%= aparelho.numero %></p>
          <% if aparelho.status == true %>
            <p>Status: Ativo</p>
          <% else %>
            <p>Status: Inativo</p>
          <% end %>
          <%= link_to "detalhes", aparelho_path(aparelho) %>
        </div>
      </div>
    <% end %>
  </div>
  <%= link_to  "Novo aparelho", new_aparelho_path, class: "btn btn-success" %>
</div>

app/views/aparelhos/new.html.erb
<div class="container mt-2 pb-2">
<h1>Cadastre um novo numero</h1>
  <%= simple_form_for @aparelho do |f| %>
    <%= f.input :numero %>
    <%= f.input :operadora %>
    <%= f.input :status, :as => :boolean, label: 'Ativo' %>
    <div class="d-flex justify-content-between">
      <%= f.submit "Cadastrar", class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/aparelhos/show.html.erb
<h1 id="show-title">Detalhes deste aparelho</h1>

<p>Numero: <%= @aparelho.numero %></p>
<p>Operadora: <%= @aparelho.operadora.capitalize %></p>

<% if @aparelho.status == true %>
  <p>Este aparelho <strong>está ativo</strong></p>
<% else %>
  <p>Este aparelho <strong>não está ativo</strong></p>
  <p><%= link_to  "Deseja ativar?", edit_aparelho_path(@aparelho), class: "btn btn-warning" %></p>
<% end %>

<p>Cadastrado desde: <%= @aparelho.created_at %></p>

<div class="show-links d-flex justify-content-between">
  <div class="back-new-links">
    <%= link_to  "Voltar", aparelhos_path, class: "btn btn-gradient"%>
  </div>
  <div class="delete-edit-link">
    <%= link_to  "Editar", edit_aparelho_path(@aparelho), class: "btn btn-secondary" %>
    <%= link_to  "Excluir", aparelho_path(@aparelho), method: :delete, class: "btn btn-danger" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Volltest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body class="container">
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Aparelhos</h1>

<%= link_to "ver todos os aparelhos cadastrados", aparelhos_path %>